### ISSUE TITLE
Not working for some article

### ISSUE THREAD

**Issue by zawawimanja** [firefinchdev/medium-unlimited-android#2]
I dont know why is the problem I  cannot read it. Some article can open but some cannot.

**Comment by firefinchdev** [comment]
Please share a link to an article, on which it is not working..?

**Comment by firefinchdev** [comment]
closing as i am not able to find an article on which it doesn't work.

**Comment by firefinchdev** [comment]
please reopen if you find some article related to this.

**Comment by ayushya19** [comment]
Hi, It's not working for me.

Please find it in the below video.

Not sure if it's because of the article.

![WhatsApp Video 2023-08-08 at 11 44 32](https://github.com/firefinchdev/medium-unlimited-android/assets/106141042/08c0b4ef-d576-487b-8e59-3dc2711d92ef)

**Comment by firefinchdev** [comment]
Medium normally unlocks the paywall if it is being visited from some Twitter page. This app simulated that behaviour by adding Referer header in http headers. But seems like Medium no longer unlocks paywall for users clicking Medium links on Twitter.

**Comment by firefinchdev** [comment]
Seems like all articles across Medium are affected, making this app useless in its current state.

**Comment by firefinchdev** [comment]
If anyone has any workaround for this, I am free to discuss the implementation.

**Comment by ayushya19** [comment]
> Medium normally unlocks the paywall if it is being visited from some Twitter page. This app simulated that behaviour by adding Referer header in http headers. But seems like Medium no longer unlocks paywall for users clicking Medium links on Twitter.

Just verified .It's not working for me too.

**Comment by ayushya19** [comment]
Website doesn't have the whole paper in the source file.

It's only partial.

![image](https://github.com/firefinchdev/medium-unlimited-android/assets/106141042/4bc17f53-5a11-4030-b6eb-051dd190accb)


We can opensource it using one of the paid accounts.
