### ISSUE TITLE
Hidden referral links in the app 

### ISSUE THREAD

**Issue by Nek-12** [firefinchdev/medium-unlimited-android#8]
The app secretly makes all links opened with this app referral links through adding the following header:

`extraHeaders = mapOf(Pair("referer", "https://t.co/je0v3782u2"))`

There is no mention of this in README.md, in the app or anywhere else.

The app must notify users of this behavior, and this must be mentioned in the readme.

The feature should be optional, ideally.

**Comment by firefinchdev** [comment]
Hi
All the magic of unlocking happens because of that line itself.
Medium allows passing the paywall if the user has clicked on the article on twitter.
And the way it detects that user is coming from twitter is using the above refer header.

**Comment by firefinchdev** [comment]
https://developer.twitter.com/en/docs/tco
Also, `https://t.co/je0v3782u2` does not point to a valid referer link. `je0v3782u2` was generated randomly.
